import { Figtree, Instrument_Serif } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/Header";
import GradualBlurMemo from "@/components/GradualBlur";
import { ReactLenis } from "lenis/react";

const figtree = Figtree({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-figtree",
});

const instrumentSerif = Instrument_Serif({
  subsets: ["latin"],
  weight: ["400"],
  style: ["normal", "italic"],
  variable: "--font-instrument-serif",
});

export const metadata = {
  title: "Tamim's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${instrumentSerif.variable} ${figtree.variable} antialiased`}
        style={{ position: "relative", height: "100vh", overflow: "hidden" }}
      >
        <ReactLenis style={{ height: "100%", overflowY: "auto" }}>
          {/* Header */}
          <Header />
          {children}
        </ReactLenis>
        <GradualBlurMemo
          target="parent"
          position="bottom"
          height="6rem"
          strength={1.5}
          divCount={5}
          curve="bezier"
          exponential={true}
          opacity={1}
        />
      </body>
    </html>
  );
}
